# Run with: docker compose --env-file {path to your env file} up
services:
  stories-ui:
    build:
      context: .
      args:
        # Build with development or production
        - NODE_ENV=production 
    image: ghcr.io/sethsterling22/stories-ui:latest
    ports:
      - '8080:80'
    env_file:
      - .env.production # Default value
    environment:
      # Manual overwrite for n8n webhook n8n and others
      - VITE_TAPIS_API_BASE_URL=${VITE_TAPIS_API_BASE_URL}
      - VITE_CKAN_BASE_URL=${VITE_CKAN_BASE_URL}
      - VITE_DYNAMO_API_BASE_URL=${VITE_DYNAMO_API_BASE_URL}
      - VITE_DYNAMO_DASHBOARD_URL=${VITE_DYNAMO_DASHBOARD_URL}
      - VITE_MAX_FILE_SIZE=${VITE_MAX_FILE_SIZE}
      - VITE_N8N_WEBHOOK_URL=${VITE_N8N_WEBHOOK_URL}

# VITE_N8N_WEBHOOK_URL="https://n8n.com/webhook"
# Must have a .env file, so you can do: "cp .env.production .env"
# sudo docker compose up --build  --force-recreate
